[tools]
deno = "latest"
node = "latest"
"npm:@fsouza/prettierd" = "latest"
"npm:oxlint" = "latest"
"npm:oxlint-tsgolint" = "latest"
"npm:shadcn" = "latest"
"npm:typescript-language-server" = "latest"
